{
    "name": "Thermal Report For Pennyuku",
    "version": "11.0.1.0.0",
    "depends": ["account_payment","account"],
    "author": "Alphasoft",
    "category": "Utilities",
    'website': 'https://www.alphasoft.co.id',
    'images':  ['images/main_screenshot.png'],
    'summary': 'Thermal Reporting',
    "description": """""",
    "data": [
        "report/payment_report.xml",
#         "report/payment_report_template.xml",
        "report/new_template.xml",
#         "view/account_payment.xml",
#         "wizard/account_payment_transient.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}